# This workflow will create new release with given tag, when a tag is pushed to master,
# will also auto generate changelog for the new release body.

name: Create Release

on:
  push:
    # branches:
      # - master
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ github.ref }}

      - name: Create new release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: true
          prerelease: false

      #   uses: ncipollo/release-action@v1
      #   with:
      #     bodyFile: "CHANGELOG.md"
      #     token: ${{ secrets.GITHUB_TOKEN }}
