# This workflow will create new release with given tag, when a tag is pushed,
# will also auto generate changelog for the new release body and update CHAGELOG.md.

name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate changelog
        id: generate
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: '.github/release_changelog.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update changelog
        uses: saadmk11/changelog-ci@v0.7.0
        with:
          changelog_filename: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: testing output
        run: |
          echo ${{ steps.generate.outputs.toTag }}
          echo ${{ steps.generate.outputs.fromTag }}
          echo ${{ steps.generate.outputs.changelog }}

      # - name: Create release
      #   uses: actions/create-release@latest
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}
      #     body: ${{ steps.generate.outputs.changelog }}
      #     prerelease: ${{ contains(github.ref, '-') }}
            # prerelease: false
      #     draft: 'true'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
