# This workflow will create new release with given tag, when a tag is pushed to master,
# will also auto generate changelog for the new release body.

name: Create Release

on:
  push:
    # branches:
      # - master
    tags:
      - 'v*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate changelog
        id: Changelog
        uses: mikepenz/release-changelog-builder-action@main
        with:
          outputFile: 'CHANGELOG.md'
          configuration: '.github/release_changelog.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate new changelog
      #   id: Changelog
      #   uses: ardalanamini/auto-changelog@v1.1.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Update changelog

      - name: Create release
        uses: actions/create-release@latest
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.Changelog.outputs.changelog }}
          prerelease: ${{ contains(github.ref, 'v?.?.?-**') }}
          draft: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
