# This workflow will create new release with given tag, when a tag is pushed,
# will also auto generate changelog for the new release body and update CHAGELOG.md.

name: Release and deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get veraion tag
        id: tag
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          output: NEW_CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Remove from changelog
        run: head -n -4 NEW_CHANGELOG.md > CHANGELOG.md

      - name: Update version
        run: sed -i -e "s/__version__.*/__version__ = '$TAG'/" mysdk/version.py
        env:
          TAG: ${{ steps.tag.outputs.SOURCE_TAG }}

      - name: Update changelog
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            CHANGELOG.md
            mysdk/version.py
          commit-msg: Update resource - workflow
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get release changelog
        run: perl -ne '$k++ if /##/; {print if $k<2}' CHANGELOG.md > RELEASE.md

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: RELEASE.md
          prerelease: ${{ contains(github.ref, '-') }}
          draft: false # true on testing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  deploy:
      needs: release
      if: contains(github.ref, '-') != true
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel twine

        - name: Build and publish
          env:
            TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          run: |
            python setup.py sdist bdist_wheel
            twine upload dist/*
