# This workflow will create new release with given tag, when a tag is pushed,
# will also auto generate changelog for the new release body and update CHAGELOG.md.

name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get veraion tag
        id: tag
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          output: NEW_CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Remove from changelog
        run: head -n -4 NEW_CHANGELOG.md > CHANGELOG.md

      - name: Update changelog
        uses: test-room-7/action-update-file@v1
        with:
          file-path: CHANGELOG.md
          commit-msg: Update changelog for mew release
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get release changelog
        run: perl -ne '$k++ if /##/; {print if $k<2}' CHANGELOG.md > RELEASE.md

      - name: Update version
        run: sed -i -e "s/__version__.*/__version__ = '$TAG'/" mysdk/version.py
        env:
          TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

      - name: Create release
        uses: actions/create-release@latest
        with:
          body_path: RELEASE.md
          prerelease: ${{ contains(github.ref, '-') }}
          draft: false # true on testing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}