# This workflow will create new release with given tag, when a tag is pushed,
# will also auto generate changelog for the new release body and update CHAGELOG.md.

name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate changelog only PR
        id: generate
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: '.github/release_changelog.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog with push
        id: changelog
        uses: ardalanamini/auto-changelog@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: "test, style"

      - name: Generate Changelog using github-changelog-generator
        uses: faberNovel/github-changelog-generator-action@v1.0.0-alpha02
          with:
            options: --token ${{ secrets.GITHUB_TOKEN }}


      # - name: Create/Update changelog
      #   uses: charmixer/auto-changelog-action@v1
      #   with:
      #     token: ${{ secrets.YOUR_GITHUB_TOKEN }}

      # - name: Commit files
      #   env:
      #     CI_USER: ${{ secrets.YOUR_GITHUB_USER }}
      #     CI_EMAIL: ${{ secrets.YOUR_GITHUB_EMAIL }}
      #   run: |
      #     git config --local user.email "$CI_EMAIL"
      #     git config --local user.name "$CI_USER"
      #     git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"

      # - name: Push changes
      #   if: env.push == 'true'
      #   env:
      #     CI_USER: ${{ secrets.YOUR_GITHUB_USER }}
      #     CI_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
      #   run: |
      #     git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master

      - name: testing output
        run: |
          echo ${{ steps.changelog.outputs.changelog }}
          echo "--- SPLIT LINE HERE ---"
          echo ${{ steps.generate.outputs.changelog }}

      # - name: Update changelog
      #   run: |


      # - name: Create release
      #   uses: actions/create-release@latest
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}
      #     body: ${{ steps.generate.outputs.changelog }}
      #     prerelease: ${{ contains(github.ref, '-') }}
            # prerelease: false
      #     draft: 'true'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
