# This workflow will run test-cases on branch on new push and pull-requests

name: Test on update

on:
  push:
  pull-request:
    branches: [master]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox pytest

      - name: Test with tox
        run: |
          tox



